site_name: Visionatrix Documentation

repo_url: https://github.com/Visionatrix/Visionatrix
repo_name: Visionatrix
edit_uri: https://github.com/Visionatrix/VixFlowsDocs/edit/main/docs/
site_url: https://visionatrix.github.io/

nav:
  - Home: index.md
  - Flows:
      - Overview: Flows/index.md
      - Colorful XL: Flows/Colorful_XL.md
      - Juggernaut Lite: Flows/Juggernaut_Lite.md
      - Juggernaut XL: Flows/Juggernaut_XL.md
      - Mobius XL: Flows/Mobius_XL.md
      - SDXL Lighting: Flows/SDXL_Lighting.md
      - Hunyuan DiT: Flows/HunyuanDiT.md
      - SD3 Medium: Flows/SD3_Medium.md
      - Stable Cascade: Flows/Stable_Cascade.md
      - Playground 2.5 Prometheus: Flows/Playground_2_5_prometheus.md
      - Playground 2.5 Aesthetic: Flows/Playground_2_5_aesthetic.md
      - Ghibli Portrait: Flows/GhibliPortrait.md
      - Comicu Portrait: Flows/ComicuPortrait.md
      - Vintage Portrait: Flows/VintagePortrait.md
      - Memoji Portrait: Flows/MemojiPortrait.md
      - Sketch Portrait: Flows/SketchPortrait.md
      - Photomaker 1: Flows/Photomaker_1.md
      - Photo Stickers: Flows/PhotoStickers.md
      - Photo Stickers 2: Flows/PhotoStickers2.md
      - Mad Scientist: Flows/MadScientist.md
      - Supir Upscaler: Flows/SupirUpscaler.md
      - Human Face Detailer: Flows/HumanFaceDetailer.md
      - Flux 1: Flows/Flux_1.md
      - Inpaint: Flows/Inpaint.md
  - Installation: installation.md
  - Working Modes: working_modes.md
  - Command Line Options: command_line_options.md
  - Technical Information: technical_information.md
  - Gated Models: gated_models.md
  - ComfyUI to Vix Workflows Migration: comfyui_vix_migration.md
  - Vix Workflows: vix_workflows.md
  - FAQ: faq.md
  - Hardware FAQ: hardware_faq.md
  - Hardware Results: hardware_results.md
  - Swagger API: swagger.html

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  logo: assets/vix_logo.png
  icon:
    repo: fontawesome/brands/github

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search
  - social


validation:
  anchors: warn
