name: Docs check
on:
  pull_request:

permissions:
  contents: read

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Docs dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Build Docs
        run: |
          python3 scripts/benchmarks/generate_hardware_results.py
          mkdocs build --strict
